add epd_powerdown for lilygo
vroland/epdiy pull request #179
Opened 2022-05-08 03:43 UTC by Yardie-

Add lilygo specific function that did my head in for a while.
When the power is turned off to the epd it seems the power to the touch screen is also disabled. Below are the notes I added.

On lilygo disable display power but not touch screen.
  The epd power flag was re-purposed as power enable
   however it also disables the touch.
  this workaround may still leave power on to epd
  and as such may cause other problems such as grey screen.
  please also use poweroff when you sleep the system
  wake on touch will still work just not the I2C interface.

2022-05-09 03:16 UTC, martinberlin approved these changes
Looks good, go ahead and merge

2022-05-09 09:52 UTC, martinberlin commented
Just add a small addition in the Readme please mentioning what is the use-case for this function.
I suggested Valentin that we start a Wiki to add specific documentation for different Boards / Epaper models but I guess that has to wait.

2022-05-09 10:37 UTC, Yardie- commented
Thanks @martinberlin. 
No worries.

2022-05-09 12:01 UTC, Yardie- commented
Ok that's done. Sorry I had to do it by hand and don't know markdown,

2022-05-10 11:52 UTC, martinberlin requested changes
Please update the readme and remove the epd_poweroff_all() since I think is a function that does not exist anymore

2022-05-10 12:25 UTC, jdoubleu commented on src/epd_driver/include/epd_driver.h
> +#if defined(CONFIG_EPD_BOARD_REVISION_LILYGO_T5_47
There's a missing `)` here, that's why the CI currently keeps failing: https://github.com/vroland/epdiy/runs/6369702620?check_suite_focus=true

2022-05-10 13:04 UTC, merged

2022-06-02 03:21 UTC, martinberlin commented
This merge in a single commit: fd8a290f68d360c33ba7833487f38566e23e7178

 was reversed since it added a function **cfg_powerdown** is a exact copy of existing funcion **cfg_poweroff**
 
 CC @mickeprag