Text background now requires EPD_DRAW_BACKGROUND
vroland/epdiy pull request #80
Opened 2021-04-23 13:02 UTC by fdev31

Now text don't have "bounding box" backgrounds painted if the EPD_DRAW_BACKGROUND flag isn't set.
Allows painting over complex images (non flat color) without visual artifacts introduction.

2021-04-24 12:57 UTC, vroland requested changes

2021-04-24 12:57 UTC, vroland commented on src/epd_driver/font.c
> +  char background_needed = props->flags & EPD_DRAW_BACKGROUND;
I'd use the bool type here for readability. Since the esp is a 32 bit system, there is no reason to prefer char.

2021-04-24 12:58 UTC, vroland commented
Looks good! I'd just do one small change: Using bool instead of char for the flag would be more readable and is irrelevant for performance. Could you change that?

2021-04-24 18:02 UTC, fdev31 commented
Just did it ;)

2021-04-25 10:43 UTC, merged

2021-04-25 10:43 UTC, vroland commented
Thanks a lot!